import type { Metadata } from "next";
import { Inter, Oswald} from "next/font/google";
import "./globals.css";
import NavBar from "./components/shared/NavBar";
import Footer from "./components/shared/Footer";
import  { WorkoutProvider } from "./context/Provider";

import { ToastContainer } from "react-toastify";



const inter = Inter({
    subsets : ['latin'],
    variable : '--font-inter'
})

const oswald = Oswald({
  subsets :['latin'],
  variable : '--font-oswald'
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html 
      lang="en"
      className={`${inter.variable} ${oswald.variable} h-full antialiased`}
    >
      <body className=" font-sans min-h-full flex flex-col bg-[#0d0e10]">

       <WorkoutProvider>


        <NavBar></NavBar>
        {children}

        <Footer></Footer>

        
      <ToastContainer
        position="top-right"
        autoClose={3000}
        hideProgressBar={false}
        newestOnTop
        closeOnClick
        pauseOnHover
        draggable
        toastClassName="!text-xs !px-3 !py-2 !min-h-0 !w-auto !max-w-[260px] sm:!max-w-sm"
        className="!top-3 !right-3 sm:!top-4 sm:!right-6"
      />


       </WorkoutProvider>
    


        
        </body>
    </html>
  );
}
