import type { Metadata } from "next";
import { Inter, Oswald} from "next/font/google";
import "./globals.css";
import NavBar from "./components/shared/NavBar";
import Footer from "./components/shared/Footer";



const inter = Inter({
    subsets : ['latin'],
    variable : '--font-inter'
})

const oswald = Oswald({
  subsets :['latin'],
  variable : '--font-oswald'
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html 
      lang="en"
      className={`${inter.variable} ${oswald.variable} h-full antialiased`}
    >
      <body className=" font-sans min-h-full flex flex-col bg-[#0d0e10]">

        <NavBar></NavBar>
        {children}

        <Footer></Footer>


        
        </body>
    </html>
  );
}
